[main]
summary=Alienware balanced profile
description=Extends the stock balanced profile with platform-profile set to balanced. Conservative CPU governor with moderate power and thermal limits.
include=balanced

[sysctl]
vm.swappiness=10

[scsi_host]
linkpowermanagement=

[acpi]
platform_profile = balanced