[main]
# The default PPD profile
default=aw-balanced
battery_detection=false
sysfs_acpi_monitor=false

[profiles]
# PPD = TuneD
power-saver=aw-powersave
balanced=aw-balanced
performance=aw-performance

[battery]
# PPD = TuneD
balanced=balanced-battery
