[main]
summary=Alienware powersave profile
description=Extends desktop-powersave with platform-profile set to balanced. Prioritizes energy efficiency for idle or light workloads.
include=desktop-powersave

[sysfs]
/sys/class/platform-profile/platform-profile-0/profile=balanced
